version: "3"
services:
  CodeByGerald:
    image: mongo
    container_name: "codeByGerald"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: springboot-test
    container_name: gerald
    ports:
      - 8000:8080
    links:
      - CodeByGerald


